-- @ 2023 César Martínez. All Copyright.
-- CREADOR DEL CÓDIGO SQL -> CÉSAR OVIDIO MARTÍNEZ CHICAS.

CREATE DATABASE SISTEMA_BANCARIO
ON PRIMARY
(NAME='SISTEMA_BANCARIO', FILENAME='D:\Sistema de Banca en C# y SQL Server\SCRIPT DATABASE\SISTEMA_BANCARIO.mdf',
SIZE =8Mb, FILEGROWTH=20%
),
FILEGROUP DATA DEFAULT
(NAME='SISTEMA_BANCARIO_Data', FILENAME='D:\Sistema de Banca en C# y SQL Server\SCRIPT DATABASE\SISTEMA_BANCARIO_Data.ndf',
SIZE =8Mb, FILEGROWTH=20%
)
LOG ON
(NAME='SISTEMA_BANCARIO_Log', FILENAME='D:\Sistema de Banca en C# y SQL Server\SCRIPT DATABASE\SISTEMA_BANCARIO_Log.ldf',
SIZE =8Mb, FILEGROWTH=20%
)
GO --SCRIPT DE CÉSAR MARTÍNEZ | CREACIÓN DE UNA BASE DE DATOS CON BUENAS PRÁCTICAS HACIENDO USO DE FILEGROUPS

USE SISTEMA_BANCARIO
GO

--------------------------------------------------------------------------------------------------------------------
-- TABLAS 
--------------------------------------------------------------------------------------------------------------------

CREATE TABLE TB_TIPO_CLIENTE(
    ID_TP_PERSONA      INT IDENTITY(1,1),
	FECHA_REGISTRO     DATETIME2 DEFAULT GETDATE(),
	TIPO_PERSONA       VARCHAR(15) NOT NULL,
	ESTADO             BIT DEFAULT 1,

	CONSTRAINT PK_TP_CLIENTE PRIMARY KEY(ID_TP_PERSONA),
	CONSTRAINT UQ_TP_CLIENTE UNIQUE (TIPO_PERSONA)
)
GO
CREATE NONCLUSTERED INDEX IX_TIPO_CLIENTE
ON TIPO_CLIENTE (ID_TP_PERSONA)
WHERE ID_TP_PERSONA >= 1;
GO

CREATE TABLE TB_CLIENTE(
   ID_CLIENTE         INT IDENTITY(1,1),
   FECHA_REGISTRO     DATETIME2 DEFAULT GETDATE(),

   ID_TP_PERSONA      INT NOT NULL, 

   NOM_CLIENTE        VARCHAR(20) NOT NULL,
   APE_PATE_CLIENTE   VARCHAR(15) NOT NULL,
   APE_MATE_CLIENTE   VARCHAR(15) NOT NULL,

   DIRECCION_CLIENTE  VARCHAR(50) NOT NULL,
   TEL_CEL_CLIENTE    VARCHAR(9) NOT NULL,
   TEL_FIJO_CLIENTE   VARCHAR(9) NOT NULL,

   DNI                VARCHAR(10) NOT NULL,  
   NOM_CARGO_CLIENTE  VARCHAR(40) NOT NULL,
   SUELDO             DECIMAL(18,2) NOT NULL,
   ESTADO             BIT DEFAULT 1,

   CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE),
   CONSTRAINT FK_TP_CLIE FOREIGN KEY (ID_TP_PERSONA) REFERENCES TIPO_CLIENTE(ID_TP_PERSONA),
   CONSTRAINT UQ_NOM_CLIENTE UNIQUE (NOM_CLIENTE, APE_PATE_CLIENTE, APE_MATE_CLIENTE)
)
GO
CREATE NONCLUSTERED INDEX IX_CLIENTE
ON CLIENTE (ID_CLIENTE)
WHERE ID_CLIENTE >= 1;
GO

CREATE TABLE TB_TIPO_CUENTA(
   ID_TIPO_CUENTA    INT IDENTITY(1,1),
   FECHA_REGISTRO    DATETIME2 DEFAULT GETDATE(),
   NOM_CUENTA        VARCHAR(12) NOT NULL,
   ESTADO            BIT DEFAULT 1,

   CONSTRAINT PK_TP_CUEN PRIMARY KEY (ID_TIPO_CUENTA),
   CONSTRAINT UQ_NOM_CUENTA UNIQUE (NOM_CUENTA)
)
GO
CREATE NONCLUSTERED INDEX IX_TIPO_CUENTA
ON TIPO_CUENTA (ID_TIPO_CUENTA)
WHERE ID_TIPO_CUENTA >= 1;
GO

CREATE TABLE TB_CUENTA(
   ID_CUENTA         INT IDENTITY(1,1),
   FECHA_REGISTRO    DATETIME2 DEFAULT GETDATE(),
   ID_TIPO_CUENTA    INT NOT NULL,
   ID_CLIENTE        INT NOT NULL,
   CODIGO_CUENTA     UNIQUEIDENTIFIER DEFAULT NEWID(),
   SALDO_ACTUAL      DECIMAL(18,2) DEFAULT 0.00,
   ESTADO            BIT DEFAULT 1,

   CONSTRAINT PK_CUENT PRIMARY KEY (ID_CUENTA),
   CONSTRAINT FK_TIP_CUEN FOREIGN KEY (ID_TIPO_CUENTA) REFERENCES TIPO_CUENTA(ID_TIPO_CUENTA),
   CONSTRAINT FK_CUEN_CLI FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE
)
GO
CREATE NONCLUSTERED INDEX IX_CUENTA
ON CUENTA (ID_CUENTA)
WHERE ID_CUENTA >= 1;
GO

CREATE TABLE TB_TIPO_TARJETA_CREDITO(
   ID_TP_TARJETA      INT IDENTITY(1,1),
   FECHA_REGISTRO     DATETIME2 DEFAULT GETDATE(),
   NOM_TARJETA        VARCHAR(10) NOT NULL,
   LIMITE             DECIMAL(18,2) NOT NULL,
   ESTADO             BIT DEFAULT 1,

   CONSTRAINT PK_ID_TARJ PRIMARY KEY (ID_TP_TARJETA),
   CONSTRAINT UQ_TP_TARJETA UNIQUE (NOM_TARJETA)
)
GO
CREATE NONCLUSTERED INDEX IX_TIPO_TARJETA_CREDITO
ON TIPO_TARJETA_CREDITO (ID_TP_TARJETA)
WHERE ID_TP_TARJETA >= 1;
GO

CREATE TABLE TB_TARJETA_CREDITO(
   ID_TARJETA_CREDITO  INT IDENTITY(1,1),
   FECHA_REGISTRO      DATETIME2 DEFAULT GETDATE(),
   ID_CLIENTE          INT NOT NULL,
   ID_CUENTA           INT NOT NULL,
   ID_TP_TARJETA       INT NOT NULL,
   CODIGO_TARJETA      UNIQUEIDENTIFIER DEFAULT NEWID(),
   SALDO_DISPONIBLE    DECIMAL(18,2) DEFAULT 0.00,
   ESTADO              BIT DEFAULT 1,

   CONSTRAINT PK_TARJ_CED PRIMARY KEY (ID_TARJETA_CREDITO),
   CONSTRAINT FK_TARJ_CLI FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
   CONSTRAINT FK_TARJ_CUEN FOREIGN KEY (ID_CUENTA) REFERENCES CUENTA (ID_CUENTA) ON DELETE CASCADE,
   CONSTRAINT FK_TP_TARJ_CRED FOREIGN KEY (ID_TP_TARJETA) REFERENCES TIPO_TARJETA_CREDITO (ID_TP_TARJETA)
)
GO
CREATE NONCLUSTERED INDEX IX_TARJETA_CREDITO
ON TARJETA_CREDITO (ID_TARJETA_CREDITO)
WHERE ID_TARJETA_CREDITO >= 1;
GO

CREATE TABLE TB_TIPO_PRESTAMO(
   ID_TP_PRESTAMO      INT IDENTITY(1,1),
   FECHA_REGISTRO      DATETIME2 DEFAULT GETDATE(),
   NOM_PRESTAMO        VARCHAR(15) NOT NULL,
   ESTADO              BIT DEFAULT 1,

   CONSTRAINT PK_TP_PREST PRIMARY KEY (ID_TP_PRESTAMO),
   CONSTRAINT UQ_TP_PRESTAMO UNIQUE (NOM_PRESTAMO)
)
GO
CREATE NONCLUSTERED INDEX IX_TIPO_PRESTAMMO
ON TIPO_PRESTAMO (ID_TP_PRESTAMO)
WHERE ID_TP_PRESTAMO >= 1;
GO

CREATE TABLE TB_TIPO_PAGO(
   ID_DIM_TP_PAGO      INT IDENTITY(1,1),
   FECHA_REGISTRO      DATETIME2 DEFAULT GETDATE(),
   TIPO_COBRO          VARCHAR(20) NOT NULL,
   ESTADO              BIT DEFAULT 1,

   CONSTRAINT PK_DIM_PAGO PRIMARY KEY (ID_DIM_TP_PAGO),
   CONSTRAINT UQ_TIPO_PAGO_PRESTAMO UNIQUE (TIPO_COBRO)
)
GO
CREATE NONCLUSTERED INDEX IX_TIPO_PAGO
ON TIPO_PAGO (ID_DIM_TP_PAGO)
WHERE ID_DIM_TP_PAGO >= 1;
GO

CREATE TABLE TB_PRESTAMO(
   ID_PRESTAMO         INT IDENTITY(1,1),
   FECHA_REGISTRO      DATETIME2 DEFAULT GETDATE(),
   ID_CLIENTE          INT NULL,
   ID_CUENTA           INT NULL,
   ID_TARJETA_CREDITO  INT NULL,
   ID_TP_PRESTAMO      INT NOT NULL,
   ID_DIM_TP_PAGO      INT NOT NULL,
   MONTO_PRESTADO      DECIMAL(18,2) DEFAULT 0.00,
   MTCN_PRESTAMO       UNIQUEIDENTIFIER DEFAULT NEWID(),
   ESTADO              BIT DEFAULT 1,

   CONSTRAINT PK_PREST PRIMARY KEY (ID_PRESTAMO),
   CONSTRAINT FK_PREST_CLIE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
   CONSTRAINT FK_PREST_CUEN FOREIGN KEY (ID_CUENTA)  REFERENCES CUENTA (ID_CUENTA),
   CONSTRAINT FK_PREST_TARJ FOREIGN KEY (ID_TARJETA_CREDITO) REFERENCES TARJETA_CREDITO (ID_TARJETA_CREDITO),
   CONSTRAINT FK_PREST_TP_PREST FOREIGN KEY (ID_TP_PRESTAMO) REFERENCES TIPO_PRESTAMO (ID_TP_PRESTAMO),
   CONSTRAINT FK_PREST_DIM_PAGO FOREIGN KEY (ID_DIM_TP_PAGO) REFERENCES TIPO_PAGO (ID_DIM_TP_PAGO)
)
GO
CREATE NONCLUSTERED INDEX IX_PRESTAMO
ON PRESTAMO (ID_PRESTAMO)
WHERE ID_PRESTAMO >= 1;
GO

CREATE TABLE TB_SUCURSAL(
   ID_SUCURSAL        INT IDENTITY(1,1),
   FECHA_REGISTRO     DATETIME2 DEFAULT GETDATE(),
   DIRECCION          VARCHAR(80) NOT NULL,
   ESTADO             BIT DEFAULT 1,

   CONSTRAINT PK_SUCURSAL PRIMARY KEY (ID_SUCURSAL)
)
GO
CREATE NONCLUSTERED INDEX IX_SUCURSAL
ON SUCURSAL (ID_SUCURSAL)
WHERE ID_SUCURSAL >= 1
GO

CREATE TABLE TB_CARGO_EMPLEADO(
   ID_CARGO_EM          INT IDENTITY(1,1),
   FECHA_REGISTRO       DATETIME2 DEFAULT GETDATE(),
   NOM_CARGO            VARCHAR(80) NOT NULL,
   ESTADO               BIT DEFAULT 1,

   CONSTRAINT PK_CARGO_EM PRIMARY KEY (ID_CARGO_EM),
   CONSTRAINT UQ_CARGO_EM UNIQUE (NOM_CARGO)
)
GO
CREATE NONCLUSTERED INDEX IX_CARGO_EMPLEADO
ON CARGO_EMPLEADO (ID_CARGO_EM)
WHERE ID_CARGO_EM >= 1;
GO

CREATE TABLE TB_USUARIO_EM(
   ID_USER              INT IDENTITY(1,1),
   FECHA_REGISTRO       DATETIME2 DEFAULT GETDATE(),
   USUARIO              VARCHAR(15) NOT NULL,
   CONTRASEÑA           VARCHAR(10) NOT NULL,
   ADMIN                BIT NOT NULL,
   PRESTAMOS            BIT NOT NULL,
   CUENTAS              BIT NOT NULL,
   TARJETAS             BIT NOT NULL,
   ESTADO               BIT DEFAULT 1,

   CONSTRAINT PK_USER PRIMARY KEY (ID_USER),
   CONSTRAINT UQ_USUARIO UNIQUE (USUARIO)
)
GO
CREATE NONCLUSTERED INDEX IX_USUARIO_EM
ON USUARIO_EM (ID_USER)
WHERE ID_USER >= 1;
GO

CREATE TABLE TB_EMPLEADO(
   ID_EM            INT IDENTITY(1,1),
   FECHA_REGISTRO   DATETIME2 DEFAULT GETDATE(),

   ID_SUCURSAL      INT NOT NULL,
   ID_CARGO_EM      INT NOT NULL,
   ID_USER          INT NOT NULL,

   NOM_EMPLEADO     VARCHAR(20)   NOT NULL,
   APE_PATE         VARCHAR(12)   NOT NULL,
   APE_MATE         VARCHAR(12)   NOT NULL,
   DIRECCION        VARCHAR(25)   NOT NULL,
   DNI_EM           VARCHAR(10)   NOT NULL,
   SUELDO           DECIMAL(18,2) NOT NULL,
   ESTADO           BIT DEFAULT 1,

   CONSTRAINT PK_EM PRIMARY KEY (ID_EM),
   CONSTRAINT FK_EM_CARGO FOREIGN KEY (ID_CARGO_EM) REFERENCES CARGO_EMPLEADO (ID_CARGO_EM),
   CONSTRAINT FK_EM_USER FOREIGN KEY (ID_USER)      REFERENCES USUARIO_EM (ID_USER),
   CONSTRAINT FK_EM_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL (ID_SUCURSAL),
   CONSTRAINT UQ_EMLEADO UNIQUE (NOM_EMPLEADO, APE_PATE, APE_MATE, DNI_EM)
)
GO
CREATE NONCLUSTERED INDEX IX_EMPELADO
ON EMPLEADO (ID_EM)
WHERE ID_EM >= 1;
GO


CREATE TABLE TB_MOVIMIENTO_ABONO(
   ID_MV_ABONO         INT IDENTITY(1,1),
   FECHA_REGISTRO      DATETIME2 DEFAULT GETDATE(),
   ID_CUENTA           INT NOT NULL,
   ID_PRESTAMO         INT NOT NULL,
   ID_CLIENTE          INT NOT NULL,
   ID_EM               INT NOT NULL,
   ID_SUCURSAL         INT NOT NULL,
   MTCN_MV_ABONO       UNIQUEIDENTIFIER DEFAULT NEWID(),
   MONTO_SALIDA        DECIMAL(18,2) DEFAULT 0.00,
   ESTADO              BIT DEFAULT 1,

   CONSTRAINT PK_MV_ABONO PRIMARY KEY (ID_MV_ABONO),
   CONSTRAINT FK_MV_ABONO_PRESTAMO FOREIGN KEY (ID_PRESTAMO) REFERENCES PRESTAMO (ID_PRESTAMO),
   CONSTRAINT FK_MV_ABONO_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL (ID_SUCURSAL),
   CONSTRAINT FK_MV_ABONO_CLIEN FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
   CONSTRAINT FK_MV_ABONO_CUENTA FOREIGN KEY (ID_CUENTA) REFERENCES CUENTA (ID_CUENTA),
   CONSTRAINT FK_MV_ABONO_EM FOREIGN KEY (ID_EM) REFERENCES EMPLEADO (ID_EM)
)
GO 
CREATE NONCLUSTERED INDEX IX_MV_ABONO
ON MOVIMIENTO_ABONO (ID_MV_ABONO)
WHERE ID_MV_ABONO >= 1
GO

CREATE TABLE TB_MOVIMIENTO_TARJETA(
   ID_MV_TARJETA       INT IDENTITY(1,1),
   FECHA_REGISTRO      DATETIME2 DEFAULT GETDATE(),
   ID_TARJETA_CREDITO  INT NOT NULL,
   ID_SUCURSAL         INT NOT NULL,
   ID_CLIENTE          INT NOT NULL,
   ID_EM               INT NOT NULL,
   MTCN_MV_TARJETA     UNIQUEIDENTIFIER DEFAULT NEWID(),
   MONTO_SALIDA        DECIMAL(18,2) DEFAULT 0.00,
   ESTADO              BIT DEFAULT 1,

   CONSTRAINT PK_MV_TARJETA PRIMARY KEY (ID_MV_TARJETA),
   CONSTRAINT FK_MvTarjeta_TARJETA FOREIGN KEY (ID_TARJETA_CREDITO) REFERENCES TARJETA_CREDITO (ID_TARJETA_CREDITO),
   CONSTRAINT FK_MvTarjeta_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL (ID_SUCURSAL),
   CONSTRAINT FK_MvTarjeta_CLIEN FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
   CONSTRAINT FK_MvTarjeta_EM FOREIGN KEY (ID_EM) REFERENCES EMPLEADO (ID_EM)
)
GO 
CREATE NONCLUSTERED INDEX IX_MV_TARJETA
ON MOVIMIENTO_TARJETA (ID_MV_TARJETA)
WHERE ID_MV_TARJETA >= 1
GO

CREATE TABLE TB_MOVIMIENTO_CUENTA(
   ID_MV_CUENTA        INT IDENTITY(1,1),
   FECHA_REGISTRO      DATETIME2 DEFAULT GETDATE(),
   ID_CUENTA           INT NOT NULL,
   ID_CLIENTE          INT NOT NULL,
   ID_EM               INT NOT NULL,
   ID_SUCURSAL         INT NOT NULL,
   MTCN_MV_CUENTA      UNIQUEIDENTIFIER DEFAULT NEWID(),
   MONTO_ENTRADA       DECIMAL(18,2) DEFAULT 0.00,
   MONTO_SALIDA        DECIMAL(18,2) DEFAULT 0.00,
   ESTADO              BIT DEFAULT 1,

   CONSTRAINT PK_MV_CUENTA PRIMARY KEY (ID_MV_CUENTA),
   CONSTRAINT FK_MvCuenta_CUENTA FOREIGN KEY (ID_CUENTA)     REFERENCES CUENTA   (ID_CUENTA),
   CONSTRAINT FK_MvCuenta_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL (ID_SUCURSAL),
   CONSTRAINT FK_MvCuenta_CLIEN FOREIGN KEY (ID_CLIENTE)     REFERENCES CLIENTE  (ID_CLIENTE),
   CONSTRAINT FK_MvCuenta_EM FOREIGN KEY (ID_EM) REFERENCES EMPLEADO (ID_EM)
)
GO 
CREATE NONCLUSTERED INDEX IX_MV_CUENTA
ON MOVIMIENTO_CUENTA (ID_MV_CUENTA)
WHERE ID_MV_CUENTA >= 1
GO
