/* CREACIÓN DE VISTAS DE SISTEMA BANCARIO */
USE SISTEMA_BANCARIO
GO
--------------------------------------------------------------------------------------------------------------------
-- VISTAS
--------------------------------------------------------------------------------------------------------------------

-- SELECT*FROM V_CLIENTE
-- SELECT*FROM V_TARJETA
-- SELECT*FROM V_PRESTAMO
-- SELECT*FROM V_EMPLEADO
-- SELECT*FROM V_CUENTA

-------------------------------------------------------------------

-------------------------------------------------------------------
CREATE VIEW V_CLIENTE AS
SELECT
    C.ID_CLIENTE,
    C.NOM_CLIENTE,
    C.APE_PATE_CLIENTE,
    C.APE_MATE_CLIENTE,
    C.DIRECCION_CLIENTE,
    C.TEL_CEL_CLIENTE,
    C.TEL_FIJO_CLIENTE,
    C.DNI,
    C.NOM_CARGO_CLIENTE,
    C.SUELDO,
	C.ESTADO,
	T.ID_TP_PERSONA,
    T.TIPO_PERSONA
FROM CLIENTE C
INNER JOIN TIPO_CLIENTE T ON C.ID_TP_PERSONA = T.ID_TP_PERSONA;
GO

CREATE VIEW V_TARJETA AS
SELECT
    T.ID_TARJETA_CREDITO,
    T.ID_CLIENTE,
    T.ID_CUENTA,
    T.CODIGO_TARJETA,
    T.SALDO_DISPONIBLE,
	T.ESTADO,
	TT.ID_TP_TARJETA,
    TT.NOM_TARJETA,
    TT.LIMITE
FROM
    TARJETA_CREDITO AS T
JOIN
    TIPO_TARJETA_CREDITO AS TT 
	ON
    T.ID_TP_TARJETA = TT.ID_TP_TARJETA;
GO

CREATE VIEW V_PRESTAMO AS
SELECT
   P.ID_CLIENTE,
   P.ID_CUENTA,
   P.MONTO_PRESTADO,
   P.MTCN_PRESTAMO,
   P.ESTADO,
   TP.ID_TP_PRESTAMO,
   TP.NOM_PRESTAMO,
   TPago.ID_DIM_TP_PAGO,
   TPago.TIPO_COBRO

FROM PRESTAMO P
INNER JOIN CLIENTE C        ON P.ID_CLIENTE     = C.ID_CLIENTE
INNER JOIN TIPO_PRESTAMO TP ON P.ID_TP_PRESTAMO = TP.ID_TP_PRESTAMO
INNER JOIN TIPO_PAGO TPago  ON P.ID_DIM_TP_PAGO = TPago.ID_DIM_TP_PAGO;
GO

CREATE VIEW V_EMPLEADO AS
SELECT
    E.ID_EM,
	E.ID_USER,
    E.NOM_EMPLEADO,
    E.APE_PATE,
    E.APE_MATE,
    E.DIRECCION,
    E.DNI_EM,
	E.SUELDO,
	E.ESTADO AS ESTADO_EM,
	CE.ID_CARGO_EM,
    CE.NOM_CARGO,
    U.USUARIO,
    U.CONTRASEÑA,
    U.ADMIN,
	U.PRESTAMOS,
	U.CUENTAS,
	U.TARJETAS,
	U.ESTADO AS ESTADO_US
	
FROM
    dbo.EMPLEADO AS E
JOIN
    dbo.CARGO_EMPLEADO AS CE ON E.ID_CARGO_EM = CE.ID_CARGO_EM
JOIN
    dbo.USUARIO_EM AS U ON E.ID_USER = U.ID_USER
GO

CREATE VIEW V_CUENTA AS
SELECT
    C.ID_CUENTA,
    C.ID_CLIENTE,
    C.CODIGO_CUENTA,
    C.SALDO_ACTUAL,
	C.ESTADO,
	TC.ID_TIPO_CUENTA,
    TC.NOM_CUENTA

FROM
    dbo.CUENTA AS C
JOIN
    dbo.TIPO_CUENTA AS TC
ON
    C.ID_TIPO_CUENTA = TC.ID_TIPO_CUENTA;
GO